### ISSUE TITLE
Task already done

### ISSUE THREAD

**Issue by shasherazi** [shasherazi/mathMagicians#4]
I already used functional components in this repo as instructed in [this activity](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_components.md). So [this day 4 task](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_refactor_with_hooks.md) is already completed. 

I am submitting this issue for review as the day 4 task instructed.

**Comment by amejid** [comment]
Hi @shasherazi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/RltjLEzzB87ErJdxHz/giphy.gif"/>

## Highlights
- App already completed with functional components :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
